version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - npm install -g serverless
      - npm install serverless-iam-roles-per-function
      - npm install serverless-python-requirements
      - npm install serverless-associate-waf
      - npm install
      - pip3 install requests
      - pip3 install aws-psycopg2
      - pip3 install python-jose
  build:
    commands:
      - serverless deploy

cache:
  paths:
    - node_modules