version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - npm install -g serverless
      - npm install
      - pip install jsonpickle
      - pip install boto3
      - pip install aws_requests_auth
      - pip install aws_lambda_powertools 
  build:
    commands:
      - serverless deploy

cache:
  paths:
    - node_modules