version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - npm install -g serverless
      - npm install serverless-python-requirements
      - npm install
  build:
    commands:
      - serverless deploy

cache:
  paths:
    - node_modules