service: OctankLMS

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.common.currentStage}

custom:
  common:
    defaultStage: dev
    region: ${opt:region, 'us-east-1'}
    currentStage: ${opt:stage, self:custom.common.defaultStage}
  stage: ${self:custom.common.currentStage}
functions:
  hello:
    handler: handler.hello

resources:
  - ${file(resources/tenants-cognito-user-pool.yml)}
  - ${file(resources/tenants-dynamodb-table.yml)}