service: OctankLMS

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.common.currentStage}
  environment:
    LOG_ENABLED: "True"
  apiGateway:
    apiKeys:
      - internal-endpoints-key
  layers:
    - Ref: PythonRequirementsLambdaLayer



package:
  patterns:
    - "!node_modules/**"
    - "!layers/**"
    - layers/base.py
    - layers/lambda_authorizer/**
    - "!.vscode"
    - "!resources/**"
    - "!*.zip"
    - "!venv/**"
    - "!README.md"
    - "!requirements.txt"
    - "!python/**"
    - "!buildspec.yml"
    - "!__pychache__/**"
    - "!package-lock.json"
    - "!package.json"

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  - serverless-associate-waf
 
custom:
  pythonRequirements:
    layer: true

  common:
    defaultStage: dev
    region: ${opt:region, 'us-east-1'}
    currentStage: ${opt:stage, self:custom.common.defaultStage}
  stage: ${self:custom.common.currentStage}
  tenantTable: ${self:custom.stage}-tenants-table
  lambdaLogsTransformedBucket: ${self:custom.stage}-lambda-logs-transformed-bucket
  logsTranformedQueue: ${self:custom.stage}-logs-transformed-queue
  acpOutputBucket: ${self:custom.stage}-acp-output-bucket
  associateWaf:
    name: ${self:custom.stage}-octank-api-waf

functions:
  - ${file(services/tenant_manager/create_tenant/function.yml)}
  - ${file(services/tenant_manager/get_tenant/function.yml)}
  - ${file(services/tenant_manager/get_tenants/function.yml)}
  - ${file(services/tenant_manager/update_tenant/function.yml)}
  - ${file(services/tenant_onboarding/function.yml)}
  - ${file(services/user_manager/create_user_group/function.yml)}
  - ${file(services/user_manager/create_user/function.yml)}
  - ${file(services/user_manager/get_users_group/function.yml)}
  - ${file(services/user_manager/get_tokens/function.yml)}
  - ${file(services/resource_manager/create_aurora_cluster/function.yml)}
  - ${file(services/resource_manager/post_aurora_creation/function.yml)}
  - ${file(services/course_manager/get_courses/function.yml)}
  - ${file(services/course_manager/get_course/function.yml)}
  - ${file(services/course_manager/create_course/function.yml)}
  - ${file(services/course_manager/grade_student/function.yml)}
  - ${file(services/tenant_cost_reporter/lambda_log_transformer/function.yml)}
  - ${file(services/tenant_cost_reporter/create_input_csv/function.yml)}
  - ${file(services/tenant_cost_reporter/queue_processor/function.yml)}
  - ${file(layers/lambda_authorizer/function.yml)}

resources:
  - ${file(resources/tenants-cognito-user-pool.yml)}
  - ${file(resources/tenants-dynamodb-table.yml)}
  - ${file(resources/rds-instance-created-event-suscription.yml)}
  - ${file(resources/rds-instance-created-sns-topic.yml)}
  - ${file(resources/api-gateway-response.yml)}
  - ${file(resources/transformed-lambda-logs-s3-bucket.yml)}
  - ${file(resources/logs-transformed-queue.yml)}
  - ${file(resources/acp-output-bucket.yml)}