service: OctankLMS

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.common.currentStage}

 
custom:
  common:
    defaultStage: dev
    region: ${opt:region, 'us-east-1'}
    currentStage: ${opt:stage, self:custom.common.defaultStage}
  stage: ${self:custom.common.currentStage}
  tenantTable: ${self:custom.stage}-tenants-table
functions:
  - ${file(services/tenant_manager/create_tenant/function.yml)}

resources:
  - ${file(resources/tenants-cognito-user-pool.yml)}
  - ${file(resources/tenants-dynamodb-table.yml)}