Resources:
  AcpOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: ${self:custom.acpOutputBucket}

  AcpOutputBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AcpOutputBucket
      PolicyDocument:
        Statement:
          - Effect: "Allow"
            Action:
              - s3:PutObject*
              - s3:GetEncryptionConfiguration
            Resource:
                - Fn::Join:
                  - ""
                  - - Fn::GetAtt: [AcpOutputBucket, Arn]
                    - "/*"
                - Fn::GetAtt: [AcpOutputBucket, Arn]
            Principal:
              Service: application-cost-profiler.amazonaws.com
            Condition:
              StringEquals:
                'aws:SourceAccount': ${aws:accountId}
              ArnEquals:
                'aws:SourceArn':
                  Fn::Join:
                  - ""
                  - - 'arn:aws:application-cost-profiler:us-east-1:'
                    - ${aws:accountId}
                    - ':*'